Interaction with database
Danila-Peshev/my-favorite-movies-back pull request #1
Opened 2024-08-28 13:11 UTC by Danila-Peshev

Added basic elements for working with the database, as well as endpoints and their processing.

2024-08-29 05:39 UTC, Isidora25 requested changes

2024-08-29 05:39 UTC, Isidora25 commented on src/auth/auth.controller.ts
> +  @Post('/login')
это нам не понадобится, так как у нас graphql по тз, можно удалять

2024-08-29 05:39 UTC, Isidora25 commented on src/auth/auth.service.ts
> +    const passwordEquals = userDto.password === user?.password;
булевы переменные обычно начинаются со слова is

2024-08-29 05:39 UTC, Isidora25 commented on src/auth/auth.service.ts
> +  }
задача validateUser только проверить, что пароли совпадают 
пусть эксепшены выбрасывает метод логина, это его задача

2024-08-29 05:39 UTC, Isidora25 commented on src/migrations/1724242104935-auto.ts
название миграции - странное
через месяц по названию не вспомнишь, что тут происходит без детального изучения кода

2024-08-29 05:39 UTC, Isidora25 commented on src/migrations/1724399693001-fill.ts
то же самое замечание про имя

2024-08-29 05:39 UTC, Isidora25 commented on src/typeorm.config.ts
> +  migrations: [join(__dirname, 'migrations', '*{.ts, .js}')],
а зачем тебе одно и то же в двух местах?

2024-08-29 05:39 UTC, Isidora25 commented on src/user-genre/userFavoriteGenre.controller.ts
мы же вроде договаривались, что перенос сервисов будет в следующем пункте тз
плюс это rest, по тз нужен graphql

2024-08-29 05:39 UTC, Isidora25 commented on src/user-genre/userFavoriteGenre.service.ts
.

2024-08-29 05:39 UTC, Isidora25 commented on src/user-movie/userFavoriteMovie.controller.ts
.

2024-08-29 05:39 UTC, Isidora25 commented on src/user-movie/userFavoriteMovie.entity.ts
тут вроде и по контексту понятно, что favorite он чей-то, то есть юзера

2024-08-29 05:39 UTC, Isidora25 commented on src/user-movie/userFavoriteMovie.service.ts
.

2024-08-29 05:39 UTC, Isidora25 commented on src/user-watched-movie/userWatchedMovie.controller.ts
.

2024-08-29 05:39 UTC, Isidora25 commented on src/user-watched-movie/userWatchedMovie.entity.ts
> +@Entity()
не нужно для этого заводить целую табличку, досточно булева флага в таблице movies

2024-08-29 05:39 UTC, Isidora25 commented on src/user-watched-movie/userWatchedMovie.service.ts
.

2024-08-29 16:12 UTC, Danila-Peshev commented on src/typeorm.config.ts
> +  migrations: [join(__dirname, 'migrations', '*{.ts, .js}')],
Один для миграций, один для взаимодействия в ходе работы
(Пытался вытащить connection данные в отдельный файл, но ts ругался когда я его использовал в TypeOrmModule)

2024-09-03 07:20 UTC, Isidora25 requested changes

2024-09-03 07:20 UTC, Isidora25 commented on src/migrations/FillingInWithPrimaryData1724399693001.ts
> +    await queryRunner.query(`
зачем тебе предзаполненные данные по фильмам?

2024-09-03 07:20 UTC, Isidora25 commented on src/typeorm.config.ts
> +const AppDataSource = new DataSource({
конфиг для базы данных должен быть один 
представь, разработчику нужно внести изменение в этот кофиг и велика вероятность, что он не будет знать про второе место.
будет исправлять и ничего не поменяется

2024-09-04 06:38 UTC, Isidora25 requested changes

2024-09-04 06:38 UTC, Isidora25 commented on src/data-source.ts
> +const AppDataSource = new DataSource({
оно тебе же вообще не нужно, у тебя есть typeOrm module, который отвечает за подключение к базе данных

2024-09-04 07:02 UTC, Isidora25 approved these changes

2024-09-04 07:14 UTC, reshetov approved these changes

2024-09-04 07:21 UTC, merged