Commit:
Danila-Peshev/my-favorite-movies-back pull request #2
Opened 2024-09-04 14:41 UTC by Danila-Peshev

Added some types for service working;
Install axios;
Added movie service and create movie module;
Added data for working with the TMDB in env.example.

2024-09-05 06:37 UTC, Isidora25 requested changes

2024-09-05 06:37 UTC, Isidora25 commented on src/tmdb-movie/movies.service.ts
> +  }
добавь обработку ошибок, на случай, если запрос упадет

2024-09-05 06:37 UTC, Isidora25 commented on src/tmdb-movie/types/SimpleMovie.ts
> +export type SimpleMovie = {
Simple не очень хорошее название, все-таки 
назови base

2024-09-06 06:04 UTC, Isidora25 approved these changes

2024-09-06 06:17 UTC, reshetov approved these changes

2024-09-06 06:17 UTC, merged