Adding graphql
Danila-Peshev/my-favorite-movies-back pull request #3
Opened 2024-09-10 04:15 UTC by Danila-Peshev

Adding graphql to backend

2024-09-10 07:07 UTC, Isidora25 requested changes

2024-09-10 07:07 UTC, Isidora25 commented on src/auth/auth.resolver.ts
> +    return optUser;
```suggestion
    return this.authService.login(email, password);
    
```

2024-09-10 07:07 UTC, Isidora25 commented on src/auth/auth.service.ts
> +}
```suggestion
  async login(email: string, password: string): Promise<User> {
  const user = await this.userService.findByEmail(email);
    const isPasswordEquals = password === user?.password;
    if (!user ||  !isPasswordEquals) {
      throw new UnauthorizedException();
    } 
    return user
  }
}
```

2024-09-10 07:07 UTC, Isidora25 commented on src/tmdb-movie/movies.resolver.ts
> +  ): Promise<MoviesResponse> {
чтобы не перечислять каждый аргумент, если их много, можно передавать параметры скопом 
https://docs.nestjs.com/graphql/resolvers#dedicated-arguments-class

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.resolver.ts
> +  }
смысловой разницы между getAllGenres  и getGenres нет, зато getGenres короче

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.resolver.ts
> +  }
я бы посоветовала не хранить в user resolver ничего, что не возвращает юзера или не меняет его 
представь, у тебя появилось 10 новых сущностей в приложении, которые связаны с юзером как-то и для каждой сущности тебе нужно написать CRUD
твой резолвер уже сейчас не маленький, а при масштабировании вообще разрастется до размеров кратера на марсе 
так что держи все что относится к отдельному домену в директории этого домена 
фильмы к фильмам, жанры к жанрам

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.resolver.ts
> +    return await this.userService.watchByMovieIdToUserByUserId(userId, movieId);
watchByMovieIdToUserByUserId - очень сложное название 
если ты напишешь markMovieWatched или что-то подобное, то смысл не поменяется, но название станет короче и чище 
пометка byMovieId или byUserId применима в том случае, когда у тебя есть альтернативы 
например, byUserEmail или что-то подобное 
у тебя же все просто пока, никаких проблем с однозначной идентификацией не дожно быть 
так что старайся Keep It Simple Stupid 
а когда понадобится, расширишь название 

ну YAGNI тут тоже применим

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.resolver.ts
> +  }
можно объединить и сделать toggleMovie

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +  }
```suggestion
  async findByEmail(email: string): Promise<User> {
    return this.userRepository.findOneBy({ email });
  }
```

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +  }
```suggestion
  async findAllGenresByUserId(userId: number): Promise<FavoriteGenre[]> {
    return = this.genreRepository.findBy({
      user: { id: userId },
    });
    return genres;
  }
```

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +    return movies;
.

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +    const user: User = await this.userRepository.findOneBy({ id: userId });
тебе не нужно делаь type assertion каждый раз 
typeorm довольно умный, чтобы возвращать нужный тип

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +  async addGenreIdToUserByUserId(
снова перегруженное название, проверь все названия сервисов

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +      const newFavoriteGenre = this.genreRepository.create({
```suggestion
      const newFavoriteGenre = await this.genreRepository.create({
```

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +        user,
тебе не нужно кидать весь объект юзера при сохранении, должно быть достаточно userId для создания связи

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +      return 'Genre has been removed';
лучше создать какой-то общий класс для ответов в случае успеха мутации, что-то типа {success: true}

2024-09-10 07:07 UTC, Isidora25 commented on src/user/user.service.ts
> +      return await this.movieRepository.save(existingFavoriteMovie);
existingFavoriteMovie.save() тоже должно работать

2024-09-10 07:43 UTC, Danila-Peshev commented on src/user/user.service.ts
> +      return await this.movieRepository.save(existingFavoriteMovie);
Нет, ругается что отсутствует сущность

2024-09-10 08:04 UTC, Danila-Peshev commented on src/user/user.service.ts
> +      const newFavoriteGenre = this.genreRepository.create({
Когда добавляю ts предупреждает:
'await' has no effect on the type of this expression.

2024-09-11 07:01 UTC, Isidora25 commented on src/movie/favorite-movie.service.ts
> +  async toggleUserMovie(
а вот тут непонятно 
toggleWatchMovie

2024-09-11 07:01 UTC, Isidora25 commented on src/movie/favorite-movie.service.ts
> +  }
это тоже можно объединить

2024-09-11 08:11 UTC, Isidora25 requested changes

2024-09-11 08:11 UTC, Isidora25 commented on src/genre/favorite-genre.service.ts
> +      await this.genreRepository.delete({ genreId });
если у тебя есть несколько юзеров, у которых один и тот же жанр в избранном, то нет гарантии, что удалится действительно у того юзера, который делал запрос, так что userId тут тоже нужен

2024-09-11 08:11 UTC, Isidora25 commented on src/genre/favorite-genre.service.ts
> +    }
```suggestion
    if (existingFavoriteGenre) {
      await this.genreRepository.delete({ genreId });
   
    } else {
      const newFavoriteGenre = this.genreRepository.create({
        user: { id: userId },
        genreId,
      });
      await this.genreRepository.save(newFavoriteGenre);
      
    }
    return { success: true };
```

2024-09-11 08:11 UTC, Isidora25 commented on src/movie/favorite-movie.service.ts
> +      await this.movieRepository.delete({ movieId });
те же замечания, что для жанров

2024-09-11 08:11 UTC, Isidora25 commented on src/movie/favorite-movie.service.ts
> +    }
```suggestion
const isWatched = existingFavoriteMovie.isWatched
   
      existingFavoriteMovie.isWatched = !isWatched;
    
```

2024-09-11 09:50 UTC, Isidora25 approved these changes

2024-09-11 10:05 UTC, reshetov requested changes

2024-09-11 10:05 UTC, reshetov commented on src/genre/favorite-genre.service.ts
> +      await this.genreRepository.save(newFavoriteGenre);
А точно save отдельно нужен, сreate не сохраняет разве сразу?

2024-09-11 10:05 UTC, reshetov commented on src/movie/favorite-movie.service.ts
> +      await this.movieRepository.save(newFavoriteMovie);
см. выше

2024-09-11 10:18 UTC, reshetov approved these changes

2024-09-11 10:18 UTC, merged